# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "SKDDJ"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 15

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "PEFT":
        filters: ["Parameter-Efficient Fine-Tuning", "PEFT", "Low-Rank Adaptation", "Efficient Fine-Tuning"]
    "Dataset Distillation":
        filters: ["Dataset Distillation", "Knowledge Distillation", "Dataset Distillation", "Data-Efficient Learning", "Data-Efficient Training", "Dataset Condensation", "Core-set Selection", "Dataset Pruning", "Data-centric AI"]
    "Schrodinger Bridge":
        filters: ["Schrodinger Bridge", "Schrödinger Bridge", "Stochastic Control", "Optimal Transport", "Diffusion Models", "Stochastic Differential Equations", "Forward-Backward SDEs", "Reversible Diffusion Processes"]
    "Text-to-Image Generation":
        filters: ["Text-to-Image Generation", "Diffusion Models", "Customization", "Zero-Shot Learning", "Generative Models"]
    "Generative Weight Space Modeling":
        filters: ["Parameter Generation",  "Model Weights Synthesis", "Weights2Weights", "Weight Space", "Semantic Weight Edits",  "Model Parameter Synthesis", "Weight Space Modeling", "Generative Weight Space"]
    "Vision-Language Models":
        filters: ["Vision-Language Models", "Multimodal Models", "Vision-and-Language", "Multimodal Learning"]
    "Synthetic Data Generation":
        filters: ["Synthetic Data", "Data Generation", "Data Synthesis"]

